### ISSUE TITLE
pls share your answer ASAP

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/StanfordAIHealthCare#1]
Introduction to Healthcare
Week 7
Final Assessment
![SNAG-0900](https://user-images.githubusercontent.com/428820/157794074-8e4ab11e-805c-4b9b-a3e7-085933f6b1cb.png)

**Comment by johnfelipe** [comment]
hi @dennislamcv1 r u there, pls share this feedback, answers pls

**Comment by dennislamcv1** [comment]
Hi @johnfelipe , sorry for my late reply as I did not enable email notice for any issues.

This is my answer:


![Final](https://user-images.githubusercontent.com/39684447/162856128-20b663de-81a4-474d-9baa-f2471997b9bd.jpg)
